name: etradebot
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.11
  - pip
  - pip:
    - cvxpy==1.3.0
    - dicttoxml==1.7.16
    - jupyterlab==3.6.1
    - keyring==23.13.1
    - matplotlib==3.7.1
    - numpy==1.24.2
    - pandas==1.5.3
    - pandas-market-calendars==4.3.3
    - pyportfolioopt==1.5.2
    - pytz==2022.7.1
    - requests==2.28.2
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - selenium==4.8.2
    - sphinx==6.1.3
    - statsmodels==0.13.5
    - tqdm==4.65.0
    - xmltodict==0.13.0
    - yahooquery==2.3.0
    - yfinance==0.2.12
    - git+https://github.com/nathanramoscfa/pyetrade.git#egg=pyetrade