name: pytest

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']

    steps:
    - uses: actions/checkout@v2

    # Set up Python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Install blpapi
    - name: Install blpapi
      run: |
        pip install --index-url=https://bcms.bloomberg.com/pip/simple/ blpapi

    # Install tia from GitHub
    - name: Install tia from GitHub
      run: |
        pip install git+https://github.com/PaulMest/tia.git#egg=tia

    # Install flake8 for linting
    - name: Install flake8
      run: pip install flake8

    # Set PYTHONPATH
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

    # Install the package in editable mode
    - name: Install Package
      run: pip install -e .

    # Lint with flake8
    - name: Lint with flake8
      run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --max-line-length=120

    # Install test dependencies
    - name: Install test dependencies
      run: |
        pip install pytest pytest-cov

    # Run tests with coverage
    - name: Run tests with coverage
      run: pytest --cov=. --cov-report=term --cov-report=xml

    # Upload coverage reports to Codecov
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
